#include "error.h"

const ERROR_CODE ERR_NONE = 0;

/* Generic errors */
const ERROR_CODE ERR_MEMFAIL = 1;;

/* Configuration errors */
#define ERR_CFG 0x000100
const ERROR_CODE ERR_CFG_NOARGS      = ERR_CFG + 1;
const ERROR_CODE ERR_CFG_HELPREQUEST = ERR_CFG + 2;

/* URL errors */
#define ERR_URL 0x000200
const ERROR_CODE ERR_URL_CANNOTPARSE = ERR_URL + 1;
const ERROR_CODE ERR_URL_NOTENOUGHDATA = ERR_URL + 2;

/* HTTP errors */
#define ERR_HTTP 0x000300
const ERROR_CODE ERR_HTTP_BLDFAIL_HDR = ERR_HTTP + 1;
const ERROR_CODE ERR_HTTP_BLDFAIL_LINE = ERR_HTTP + 2;
const ERROR_CODE ERR_HTTP_BLDFAIL_RQST = ERR_HTTP + 3;

/* Net errors */
#define ERR_NET 0x000400
const ERROR_CODE ERR_NET_ADDRFAIL = ERR_NET + 1;
const ERROR_CODE ERR_NET_CONNFAIL = ERR_NET + 2;
const ERROR_CODE ERR_NET_SOCKNOTVALID = ERR_NET + 3;
const ERROR_CODE ERR_NET_SENDFAIL = ERR_NET + 4;
const ERROR_CODE ERR_NET_RECVFAIL = ERR_NET + 5;
const ERROR_CODE ERR_NET_CONNCLOSED = ERR_NET + 6;
