#ifndef CLIHT_ERROR_H_
#define CLIHT_ERROR_H_

typedef unsigned int ERROR_CODE;

extern const ERROR_CODE ERR_NONE;

extern const ERROR_CODE ERR_MEMFAIL;

extern const ERROR_CODE ERR_CFG_NOARGS;
extern const ERROR_CODE ERR_CFG_HELPREQUEST;

extern const ERROR_CODE ERR_URL_CANNOTPARSE;
extern const ERROR_CODE ERR_URL_NOTENOUGHDATA;

extern const ERROR_CODE ERR_HTTP_BLDFAIL_HDR;
extern const ERROR_CODE ERR_HTTP_BLDFAIL_LINE;
extern const ERROR_CODE ERR_HTTP_BLDFAIL_RQST;

extern const ERROR_CODE ERR_NET_ADDRFAIL;
extern const ERROR_CODE ERR_NET_CONNFAIL;
extern const ERROR_CODE ERR_NET_SOCKNOTVALID;
extern const ERROR_CODE ERR_NET_SENDFAIL;
extern const ERROR_CODE ERR_NET_RECVFAIL;
extern const ERROR_CODE ERR_NET_CONNCLOSED;

#endif // CLIHT_ERROR_H_
